name: 每日兩次抓取氣象資料

on:
  schedule:
    - cron: '0 22 * * *'  # 台灣早上 6 點
    - cron: '0 10 * * *'  # 台灣下午 6 點
  workflow_dispatch:

jobs:
  run-weather-script:
    runs-on: ubuntu-latest

    steps:
    - name: 下載程式碼
      uses: actions/checkout@v3

    - name: 安裝 Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: 安裝依賴套件
      run: |
        python -m pip install --upgrade pip
        pip install gspread oauth2client requests beautifulsoup4 pandas

    - name: 建立憑證檔案
      run: |
        echo "${{ secrets.GS_CREDENTIALS }}" > trn3-466407-aee04859332a.json

    - name: 執行主程式
      run: python main.py
