name: 每日兩次抓取氣象資料

on:
  schedule:
    - cron: '0 22 * * *'  # 台灣早上 6 點
    - cron: '0 10 * * *'  # 台灣下午 6 點
  workflow_dispatch:

jobs:
  run-weather-script:
    runs-on: ubuntu-latest

    steps:
    - name: 下載程式碼
      uses: actions/checkout@v3

    - name: 安裝 Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: 安裝必要套件
      run: |
        python -m pip install --upgrade pip
        pip install gspread oauth2client requests beautifulsoup4 pandas
        pip install selenium

    - name: 建立憑證JSON檔
      run: |
        echo "${{ secrets.GCP_CREDENTIALS_JSON }}" > service_account.json

    - name: 執行主程式
      run: python main.py
